### ISSUE TITLE
Would be nice to have it python 3 compatible

### ISSUE THREAD

**Issue by mab-u** [fracpete/python-weka-wrapper#20]
@fracpete can't install in an easy way with python 3.x
`$ pip install python-weka-wrapper`

``` bash
Downloading/unpacking python-weka-wrapper
  Downloading python-weka-wrapper-0.1.12.tar.gz (43kB): 43kB downloaded
  Running setup.py egg_info for package python-weka-wrapper
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "C:\Users\[...]\AppData\Local\Temp\pip_build_[...]\python-weka-
wrapper\setup.py", line 36
        print "Downloading '" + url + "' to '" + outfile + "'"
                            ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "C:\Users\[...]\AppData\Local\Temp\pip_build_[...]\python-weka-wrap
per\setup.py", line 36

    print "Downloading '" + url + "' to '" + outfile + "'"

                        ^

SyntaxError: invalid syntax
```

**Comment by fracpete** [comment]
There is an experimental Python3 port now available:
https://github.com/fracpete/python-weka-wrapper3
